# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 05:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default=datetime.datetime(2018, 5, 17, 5, 34, 22, 175466, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
